### ISSUE TITLE
[inf nan] got `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by yunyipower** [mit-han-lab/qserve#38]
[env]
using nvcr.io/nvidia/pytorch:23.06-py3 to create a container

cd /home/zhouyou09/
git clone https://github.com/mit-han-lab/qserve
cd qserve
conda create -n QServe python=3.10 -y
conda activate QServe
conda deactivate # maybe
conda install -c nvidia cuda-toolkit -y
pip3 install -e .
pip3 install flash-attn --no-build-isolation

git clone https://github.com/NVlabs/VILA
cd VILA
pip3 install https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
# Install VILA
pip3 install -e .
pip3 install -e ".[train]"

cd /home/zhouyou09/qserve
cd kernels
python3 setup.py install

[problem description]

[Warmup Round 0]
INFO 09-07 13:45:22 llm_engine.py:122] Initializing an LLM engine with config: model='/home/qserve_checkpoints/Llama-3-8B-QServe', tokenizer='/home/qserve_checkpoints/Llama-3-8B-QServe', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=int8, device_config=cuda, ifb_config=False, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/root/anaconda3/envs/QServe/lib/python3.10/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
[2024-09-07 13:45:24,497] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[INFO] Using w4a8kv4 precision
INFO 09-07 13:45:34 model_runner.py:310] # GPU blocks: 6400, # CPU blocks: 10
[INFO] USE INT4 w/ ZERO_POINTS for KV CACHE
Running without ifb mode
Running with benchmarking mode
torch.Size([4, 2, 24])
Traceback (most recent call last):
  File "/home/qserve/qserve_benchmark.py", line 128, in <module>
    main(args)
  File "/home/qserve/qserve_benchmark.py", line 98, in main
    time_lis, num_tokens = process_requests(
  File "/home/qserve/qserve_benchmark.py", line 55, in process_requests
    requests_outputs = engine.step()
  File "/home/qserve/qserve/engine/llm_engine.py", line 621, in step
    all_outputs = self._run_workers(
  File "/home/qserve/qserve/engine/llm_engine.py", line 737, in _run_workers
    output = executor(*args, **kwargs)
  File "/root/anaconda3/envs/QServe/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/qserve/qserve/worker/worker.py", line 247, in execute_model
    output = self.model_runner.execute_model(
  File "/root/anaconda3/envs/QServe/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/qserve/qserve/worker/model_runner.py", line 664, in execute_model
    tokens = model.sample(input_tokens, output, input_metadata)
  File "/home/qserve/qserve/modeling/models/llama_w4a8_unpad.py", line 485, in sample
    return self.sampler(input_ids, logits, input_metadata)
  File "/root/anaconda3/envs/QServe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/QServe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qserve/qserve/modeling/layers/sampler.py", line 92, in forward
    token = torch.multinomial(probs, num_samples=1).view(-1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by ys-2020** [comment]
Hi, 

Thanks for your interests in QServe. When running the benchmarking code, we use random weight initialization. Thus, getting inf/nan in output logits is expected. Please refer to [this PR](https://github.com/mit-han-lab/qserve/pull/37/files#diff-923f295761bd6ddac4b5e9bf1a7ed0b5f51dee18a5923aef657ed51e6ec0a29eR87) to activate greedy sampling when running benchmarking code. We will make a better fix to this problem in the next release.
